SELECT
    IDX,
    TITLE,
    HIT_CNT,
    CREA_DTM
FROM
    TB_BOARD
ORDER BY IDX DESC

CREATE TABLE TB_FILE
(
  IDX   INT auto_increment,
  BOARD_IDX INT NOT NULL,
  ORIGINAL_FILE_NAME VARCHAR(260) NOT NULL,
  STORED_FILE_NAME VARCHAR(36) NOT NULL,
  FILE_SIZE INT,
  CREA_DTM  TIMESTAMP  DEFAULT NOW() NOT NULL,
  CREA_ID   VARCHAR(30) NOT NULL,
  DEL_GB    VARCHAR(1) DEFAULT 'N' NOT NULL,
  PRIMARY KEY (IDX)
);

select * from TB_BOARD;
  INSERT INTO TB_BOARD(TITLE, CONTENTS, HIT_CNT, DEL_GB, CREA_DTM, CREA_ID) VALUES('제목  ', '내용 ', 0, 'N', NOW(), 'Admin');
BEGIN
    FOR i IN 1..500 LOOP
    INSERT INTO TB_BOARD(TITLE, CONTENTS, HIT_CNT, DEL_GB, CREA_DTM, CREA_ID) VALUES(CONCAT('제목  ', i), CONCAT('내용 ', i), 0, 'N', NOW(), 'Admin');
    END LOOP;
END;

SELECT
		(SELECT COUNT(0) FROM TB_board WHERE DEL_GB = 'N') AS TOTAL_COUNT ,
		IDX,
		TITLE,
		HIT_CNT,
		CREA_DTM
		FROM
		TB_board
		WHERE
		DEL_GB= 'N'
		ORDER BY IDX DESC
     
		Limit 15 , 15


